mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50
  left_wheel: 'f_left_wheel'
  right_wheel: 'f_right_wheel'
  wheel_separation: 1.0380
  wheel_radius : 0.200
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  base_frame_id: base_link_odom
  
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 1.0

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

gazebo_ros_control:
  pid_gains:
    f_left_wheel: {p: 15, i: 0.02, d: 0.001}
    f_right_wheel: {p: 15, i: 0.02, d: 0.001}
    servo: {p: 2, i: 0.02, d: 0.1}
